# Generated by Django 3.1 on 2022-03-31 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220328_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_editing',
        ),
        migrations.AddField(
            model_name='review',
            name='date_edited',
            field=models.DateTimeField(help_text='The date and time the review was last edited.', null=True),
        ),
        migrations.AlterField(
            model_name='bookcontributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co-Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role this contributor had in the book.'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='email',
            field=models.EmailField(help_text='The contact email for the contributor.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='first_names',
            field=models.CharField(help_text="The contributor's first name or names.", max_length=50),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='last_names',
            field=models.CharField(help_text="The contributor's last name or names.", max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(help_text="The Publisher's website."),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(help_text='The Book that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='reviews.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the review was created.'),
        ),
    ]
